const { z } = require("zod");
const suggestion = z.object({ title: z.string().min(3).max(200), detail: z.string().min(5).max(2000), severity: z.enum(["critical", "high", "medium", "low"]), evidence: z.string().max(1000).optional(), confidence: z.number().min(0).max(1) });
const schemas = {
    resume_extraction: z.object({ confidence: z.number().min(0).max(1), contact: z.object({ email: z.string().nullable(), phone: z.string().nullable(), linkedin: z.string().nullable(), github: z.string().nullable(), portfolio: z.string().nullable() }), skills: z.array(z.object({ name: z.string().max(100), confidence: z.number().min(0).max(1), evidence: z.string().max(500) })).max(100), experienceYears: z.number().min(0).max(80).nullable(), education: z.array(z.object({ degree: z.string().max(200), field: z.string().max(200), institution: z.string().max(300), evidence: z.string().max(500) })).max(30), experiences: z.array(z.object({ title: z.string().max(200), company: z.string().max(200), description: z.string().max(2000), evidence: z.string().max(500) })).max(50), warnings: z.array(z.string().max(500)).max(20) }),
    resume_improvement: z.object({ confidence: z.number().min(0).max(1), suggestions: z.array(suggestion).max(20), strengths: z.array(z.string().max(500)).max(10), uncertainties: z.array(z.string().max(500)).max(10) }),
    jd_parse: z.object({ confidence: z.number().min(0).max(1), title: z.string().max(150), responsibilities: z.array(z.string().max(1000)).max(30), requiredSkills: z.array(z.string().max(100)).max(50), preferredSkills: z.array(z.string().max(100)).max(50), experienceYears: z.number().min(0).max(50).nullable(), uncertainties: z.array(z.string().max(500)).max(10) }),
    jd_improvement: z.object({ confidence: z.number().min(0).max(1), improvedDescription: z.string().min(20).max(20000), suggestions: z.array(suggestion).max(20), biasWarnings: z.array(z.string().max(500)).max(20), uncertainties: z.array(z.string().max(500)).max(10) }),
    interview_questions: z.object({ confidence: z.number().min(0).max(1), questions: z.array(z.object({ competency: z.string().max(100), question: z.string().max(1000), followUps: z.array(z.string().max(500)).max(5), rubric: z.array(z.string().max(500)).max(5) })).min(1).max(20), limitations: z.array(z.string().max(500)).max(10) }),
    interview_preparation: z.object({ confidence: z.number().min(0).max(1), focusAreas: z.array(z.string().max(500)).max(15), practiceQuestions: z.array(z.string().max(1000)).max(20), skillGaps: z.array(z.string().max(200)).max(20), limitations: z.array(z.string().max(500)).max(10) }),
    recruiter_copilot: z.object({ confidence: z.number().min(0).max(1), answer: z.string().max(5000), citations: z.array(z.string().max(200)).max(20), proposedActions: z.array(z.object({ type: z.string().max(100), description: z.string().max(500), requiresConfirmation: z.literal(true) })).max(10), limitations: z.array(z.string().max(500)).max(10) }),
    career_copilot: z.object({ confidence: z.number().min(0).max(1), answer: z.string().max(5000), recommendations: z.array(z.string().max(1000)).max(20), citations: z.array(z.string().max(200)).max(20), limitations: z.array(z.string().max(500)).max(10) }),
};
module.exports = { schemas };
