import { AlertTriangle, ArrowRight, Bot, CheckCircle2, CircleDashed, Clock3, Info, XCircle } from "lucide-react";
import { Link } from "react-router-dom";
import Badge from "./ui/Badge";
import Button from "./ui/Button";
import { cn, formatRelativeTime } from "../lib/utils";

export const PageHeader = ({ eyebrow, title, description, action }) => <header className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">{eyebrow}</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-ink-950 sm:text-3xl">{title}</h1>{description && <p className="mt-2 max-w-2xl text-sm leading-6 text-ink-500 sm:text-base">{description}</p>}</div>{action && <div className="shrink-0">{action}</div>}</header>;
export const Metric = ({ label, value, detail, tone = "ink" }) => <div className="border-l-2 border-ink-200 pl-4"><p className="text-xs font-semibold uppercase tracking-wider text-ink-400">{label}</p><p className={cn("mt-1 text-2xl font-bold tabular-nums", tone === "brand" ? "text-brand-700" : tone === "success" ? "text-success-700" : "text-ink-950")}>{value}</p>{detail && <p className="mt-1 text-xs text-ink-500">{detail}</p>}</div>;
export const AIProvenance = ({ metadata, confidence, limitations = [] }) => <div className="rounded-xl border border-white/10 bg-white/5 p-4 text-sm"><div className="flex flex-wrap items-center gap-2"><Bot className="h-4 w-4 text-cyan-300" /><span className="font-semibold">AI result</span>{confidence !== undefined && confidence !== null && <Badge variant="outline">{Math.round(confidence * 100)}% confidence</Badge>}{metadata?.fallbackUsed && <Badge variant="warning">Deterministic fallback</Badge>}</div>{metadata && <p className="mt-2 text-xs text-ink-400">{metadata.provider} · {metadata.model} · prompt {metadata.promptVersion}</p>}{limitations.length > 0 && <ul className="mt-3 space-y-1 text-xs text-ink-300">{limitations.map((item) => <li key={item} className="flex gap-2"><Info className="mt-0.5 h-3.5 w-3.5 shrink-0" />{item}</li>)}</ul>}</div>;
const scoreTone = (score) => score >= 80 ? "text-success-700 bg-success-50" : score >= 60 ? "text-brand-700 bg-brand-50" : score >= 40 ? "text-warning-700 bg-warning-50" : "text-danger-700 bg-danger-50";
export const HybridMatch = ({ match, compact = false }) => { if (!match) return null; const components = match.componentScores || {}; return <div className="space-y-5"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><div className={cn("grid h-28 w-28 shrink-0 place-items-center rounded-full border-8 border-white shadow-sm", scoreTone(match.overallScore))}><div className="text-center"><div className="text-3xl font-bold">{match.overallScore}</div><div className="text-[10px] font-bold uppercase">fit score</div></div></div><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-bold capitalize">{String(match.recommendation || "Fit analysis").replaceAll("_", " ")}</h3><Badge variant="outline">{Math.round((match.confidence || 0) * 100)}% confidence</Badge></div><div className="mt-3 flex flex-wrap gap-2">{(match.matchedSkills || []).slice(0, 8).map((skill) => <Badge key={skill} variant="success">{skill}</Badge>)}</div></div></div>{!compact && <><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(components).map(([key, value]) => <div key={key} className="rounded-xl border border-ink-200 bg-white p-3"><div className="flex justify-between text-xs"><span className="font-semibold capitalize text-ink-600">{key.replace(/([A-Z])/g," $1")}</span><span className="font-bold">{value.score}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-ink-100"><div className="h-full rounded-full bg-brand-500" style={{ width: `${value.score}%` }} /></div></div>)}</div><div className="grid gap-4 md:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-wider text-danger-700">Missing required</p><div className="mt-2 flex flex-wrap gap-2">{match.missingRequiredSkills?.length ? match.missingRequiredSkills.map((s) => <Badge key={s} variant="danger">{s}</Badge>) : <span className="text-sm text-ink-500">No required skill gaps detected.</span>}</div></div><div><p className="text-xs font-bold uppercase tracking-wider text-warning-700">Concerns</p><ul className="mt-2 space-y-1 text-sm text-ink-600">{(match.concerns || []).map((x) => <li key={x}>• {x}</li>)}{!match.concerns?.length && <li>No major concerns identified.</li>}</ul></div></div><div className="rounded-xl bg-ink-50 p-4 text-sm text-ink-600"><p className="font-semibold text-ink-900">Evidence & limitations</p><p className="mt-1">Semantic method: {match.semanticEvidence?.method || "not available"}. Experience: {match.experienceEvidence?.candidateYears ?? "uncertain"} years against {match.experienceEvidence?.requiredYears ?? "no explicit minimum"}.</p><ul className="mt-2">{(match.limitations || []).map((x) => <li key={x}>• {x}</li>)}</ul></div></>}</div>; };
export const StatusPill = ({ status }) => { const s = String(status || "unknown"); const map = { ready:[CheckCircle2,"success"],completed:[CheckCircle2,"success"],hired:[CheckCircle2,"success"],failed:[XCircle,"danger"],rejected:[XCircle,"danger"],processing:[CircleDashed,"brand"],queued:[Clock3,"warning"],interview:[Clock3,"warning"],shortlisted:[CheckCircle2,"brand"] }; const [Icon, variant] = map[s] || [Info,"default"]; return <Badge variant={variant}><Icon className="mr-1 h-3 w-3" />{s.replaceAll("_", " ")}</Badge>; };
export const JobTile = ({ job, match, saved, onSave }) => { const jobId = job.id || job._id; const href = !match && !onSave ? `/jobs/${jobId}` : `/app/candidate/jobs/${jobId}`; const skills = job.requiredSkills || job.skills || []; return <article className="panel p-5 transition hover:-translate-y-0.5 hover:border-brand-200 hover:shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-brand-600">{job.workplaceMode || job.jobType}</p><h3 className="mt-1 text-lg font-bold"><Link to={href} className="hover:text-brand-600">{job.title}</Link></h3><p className="mt-1 text-sm text-ink-500">{job.company} · {job.location}</p></div>{match && <div className={cn("rounded-xl px-3 py-2 text-center", scoreTone(match.overallScore))}><div className="text-xl font-bold">{match.overallScore}</div><div className="text-[10px] font-bold uppercase">fit</div></div>}</div><p className="mt-3 line-clamp-2 text-sm leading-6 text-ink-600">{job.description}</p><div className="mt-3 flex flex-wrap gap-1.5">{skills.slice(0,5).map((skill) => <Badge key={skill}>{skill}</Badge>)}</div><div className="mt-5 flex items-center gap-2"><Button as={Link} to={href} size="sm">View fit <ArrowRight className="h-3.5 w-3.5" /></Button>{onSave && <Button variant="ghost" size="sm" onClick={() => onSave(jobId)}>{saved ? "Saved" : "Save"}</Button>}<span className="ml-auto text-xs text-ink-400">{job.createdAt ? formatRelativeTime(job.createdAt) : "Open"}</span></div></article>; };
export const ErrorCallout = ({ error }) => <div role="alert" className="flex gap-3 rounded-xl border border-danger-500/20 bg-danger-50 p-4 text-sm text-danger-700"><AlertTriangle className="h-5 w-5 shrink-0" /><div><p className="font-semibold">This action did not complete</p><p>{error?.message || "Please try again."}</p>{error?.requestId && <p className="mt-1 font-mono text-xs">Request {error.requestId}</p>}</div></div>;
